# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\PyQt5\test.ui\add1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(585, 538)
        dialog.setMinimumSize(QtCore.QSize(585, 538))
        dialog.setMaximumSize(QtCore.QSize(585, 538))
        dialog.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.graphicsView = QtWidgets.QGraphicsView(dialog)
        self.graphicsView.setGeometry(QtCore.QRect(60, 40, 31, 31))
        self.graphicsView.setStyleSheet("border-image: url(./piliang_ico/ID.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit1 = QtWidgets.QLineEdit(dialog)
        self.lineEdit1.setGeometry(QtCore.QRect(170, 40, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(110, 50, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.lineEdit2 = QtWidgets.QLineEdit(dialog)
        self.lineEdit2.setGeometry(QtCore.QRect(170, 100, 361, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(60, 100, 31, 31))
        self.graphicsView_2.setStyleSheet("border-image: url(./piliang_ico/name.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(60, 160, 31, 31))
        self.graphicsView_3.setStyleSheet("border-image: url(./piliang_ico/Sex.net.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 170, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox1 = QtWidgets.QComboBox(dialog)
        self.comboBox1.setGeometry(QtCore.QRect(170, 161, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox1.setFont(font)
        self.comboBox1.setObjectName("comboBox1")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./piliang_ico/Male.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox1.addItem(icon, "")
        self.comboBox1.setItemText(0, "男")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./piliang_ico/Female.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox1.addItem(icon1, "")
        self.graphicsView_4 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(60, 220, 31, 31))
        self.graphicsView_4.setStyleSheet("border-image: url(./piliang_ico/age.net.png);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 230, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox2 = QtWidgets.QComboBox(dialog)
        self.comboBox2.setGeometry(QtCore.QRect(170, 230, 69, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.graphicsView_5 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_5.setGeometry(QtCore.QRect(60, 280, 31, 31))
        self.graphicsView_5.setStyleSheet("border-image: url(./piliang_ico/time.net.png);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 290, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(dialog)
        self.dateEdit.setGeometry(QtCore.QRect(200, 290, 130, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit3 = QtWidgets.QLineEdit(dialog)
        self.lineEdit3.setGeometry(QtCore.QRect(170, 330, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.graphicsView_6 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_6.setGeometry(QtCore.QRect(60, 330, 31, 31))
        self.graphicsView_6.setStyleSheet("border-image: url(./piliang_ico/postbox.net.png);")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.label_6 = QtWidgets.QLabel(dialog)
        self.label_6.setGeometry(QtCore.QRect(110, 340, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit4 = QtWidgets.QLineEdit(dialog)
        self.lineEdit4.setGeometry(QtCore.QRect(170, 390, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.graphicsView_7 = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_7.setGeometry(QtCore.QRect(60, 390, 31, 31))
        self.graphicsView_7.setStyleSheet("border-image: url(./piliang_ico/telephone.png);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.label_7 = QtWidgets.QLabel(dialog)
        self.label_7.setGeometry(QtCore.QRect(110, 400, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 460, 91, 41))
        self.pushButton.setStyleSheet("image: url(./piliang_ico/confirm.net.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "手动添加"))
        self.label.setText(_translate("dialog", "学号："))
        self.label_2.setText(_translate("dialog", "姓名："))
        self.label_3.setText(_translate("dialog", "性别："))
        self.comboBox1.setItemText(1, _translate("dialog", "女"))
        self.label_4.setText(_translate("dialog", "年龄："))
        self.comboBox2.setItemText(0, _translate("dialog", "16"))
        self.comboBox2.setItemText(1, _translate("dialog", "17"))
        self.comboBox2.setItemText(2, _translate("dialog", "18"))
        self.comboBox2.setItemText(3, _translate("dialog", "19"))
        self.comboBox2.setItemText(4, _translate("dialog", "20"))
        self.comboBox2.setItemText(5, _translate("dialog", "21"))
        self.comboBox2.setItemText(6, _translate("dialog", "22"))
        self.comboBox2.setItemText(7, _translate("dialog", "23"))
        self.comboBox2.setItemText(8, _translate("dialog", "24"))
        self.comboBox2.setItemText(9, _translate("dialog", "25"))
        self.comboBox2.setItemText(10, _translate("dialog", "26"))
        self.comboBox2.setItemText(11, _translate("dialog", "27"))
        self.comboBox2.setItemText(12, _translate("dialog", "28"))
        self.comboBox2.setItemText(13, _translate("dialog", "29"))
        self.comboBox2.setItemText(14, _translate("dialog", "30"))
        self.label_5.setText(_translate("dialog", "出生年月："))
        self.label_6.setText(_translate("dialog", "E-mail："))
        self.label_7.setText(_translate("dialog", "电话："))


buttonstyle="""
padding-left: 10px;
padding-right: 10px;
padding-top: 1px;
padding-bottom: 1px;
border:3px solid orange;
border-radius:15px;
background: lightgray;
image: url(./piliang_ico/confirm.net.png);
color: white;
"""
class Add_d1(QtWidgets.QMainWindow, Ui_dialog):
    def __init__(self):
        super(Add_d1, self).__init__()
        self.setupUi(self)
        self.pushButton.setStyleSheet(buttonstyle)
        self.setWindowIcon(QIcon('./piliang_ico/export.png'))

